# Generated by Django 4.0.4 on 2022-06-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceapps',
            name='change_description',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x7fb80a6f7eb0>', max_length=150),
        ),
    ]
