# Generated by Django 4.0.4 on 2022-06-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_apps', '0002_alter_serviceapps_change_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceapps',
            name='change_description',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x7f5c95ee9eb0>', max_length=150),
        ),
    ]
