# Generated by Django 4.0.4 on 2022-07-07 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service_apps', '0003_alter_serviceapp_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceapp',
            name='app_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
