# Generated by Django 4.0.4 on 2022-06-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_apps', '0004_serviceapps_app_name_alter_serviceapps_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceapps',
            name='change_description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='serviceapps',
            name='creator',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
