# Generated by Django 4.0.4 on 2022-06-30 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('AIRTIME', 'Airtime'), ('SEND_MONEY', 'Send Money'), ('BUY_GOODS', 'Buy Goods'), ('PAYBILL', 'Paybill')], max_length=30)),
                ('status', models.CharField(choices=[('Successful', 'Successful'), ('Failed', 'Failed'), ('PendingInternal', 'Pending Internal'), ('PendingExternal', 'Pending External'), ('NotAvailable', 'Na')], max_length=30)),
                ('response_code', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service_apps.serviceapp')),
            ],
            options={
                'verbose_name_plural': 'transactions',
                'db_table': 'transactions',
                'ordering': ['-updated_at'],
            },
        ),
    ]
