# Generated by Django 4.0.4 on 2022-07-01 12:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service_transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('74355914-5c9f-459a-9543-cff84120c411'), editable=False, primary_key=True, serialize=False),
        ),
    ]
