# Generated by Django 4.0.4 on 2022-07-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_transactions', '0002_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Successful', 'Successful'), ('Failed', 'Failed'), ('PendingInternal', 'Pending Internal'), ('PendingExternal', 'Pending External'), ('NotAvailable', 'Na')], default='PendingInternal', max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
