# Generated by Django 4.0.4 on 2022-07-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_transactions', '0003_transaction_transaction_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='response_message',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
