version: 1
formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%d-%b-%y %H:%M:%S'
  brief:
    format: '%(message)s'
handlers:
  console:
    class:  logging.StreamHandler 
    formatter : brief
  file:
    class:  logging.FileHandler 
    (): log_config.make_logger
    formatter: default
loggers:
  RootLogger: 
    level: DEBUG
    handlers: [console,file]
