# Generated by Django 4.0.4 on 2022-06-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_rename_application_serviceapps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceapps',
            name='active',
            field=models.BooleanField(),
        ),
    ]
