# Generated by Django 4.0.4 on 2022-06-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_alter_serviceapps_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='response_code',
            field=models.IntegerField(null=True),
        ),
    ]
